COMMON: &common
  SECRET_KEY: insecure
  SECURITY_POST_LOGIN_VIEW: '/profile'
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@192.168.0.10:5432/flask_social_example_development
  ADMIN_CREDENTIALS: 'admin,password'
  SECURITY_TRACKABLE: True

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'sqlite:////database.sqlite'

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  JSONIFY_PRETTYPRINT_REGULAR: True

TESTING: &testing
  <<: *common
  SERVER_NAME: 'locahost'
  SQLALCHEMY_DATABASE_URI: 'sqlite:///:memory:'
  TESTING: True

